compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org/"

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmPublishRegistry: "${NPM_PUBLISH_REGISTRY:-}"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
