nodeLinker: node-modules

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmPublishRegistry: "${NPM_PUBLISH_REGISTRY:-}"

npmAuditRegistry: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
